package:
  name: alethic-ism-db
  version: 0.0.1
source:
  path: ../
build:
  # Uncomment the following line if your package is pure Python.
  noarch: python
  number: 1040
  # If you need MAKEFLAGS for building native code, you can leave it:
  # script_env:
  #   - MAKEFLAGS=-j$(nproc)
  # The pip flags below ensure dependencies are managed by conda:
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
requirements:
  host:
    - python >=3.7 # Adjust the Python version as needed
    - pip
    - setuptools
  run:
    - python >=3.7
about:
  home: https://github.com/quantumwake/alethic-ism-db
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: "Alethic - Instruction-Based State Machine (Backend)"
