----------------------------------------
------ USAGE TIER ------
----------------------------------------
CREATE TABLE IF NOT EXISTS USAGE_TIER (
  ID VARCHAR(64) PRIMARY KEY,
  -- UNIT CAPS (NULL = UNLIMITED)
  PER_MINUTE BIGINT CHECK (PER_MINUTE IS NULL OR PER_MINUTE >= 0),
  PER_HOUR   BIGINT CHECK (PER_HOUR   IS NULL OR PER_HOUR   >= 0),
  PER_DAY    BIGINT CHECK (PER_DAY    IS NULL OR PER_DAY    >= 0),
  PER_MONTH  BIGINT CHECK (PER_MONTH  IS NULL OR PER_MONTH  >= 0),
  PER_YEAR   BIGINT CHECK (PER_YEAR   IS NULL OR PER_YEAR   >= 0),

  -- COST CAPS (NULL = UNLIMITED). CURRENCY IN YOUR ROLL-UPS (E.G., USD).
  COST_PER_MINUTE   NUMERIC CHECK (COST_PER_MINUTE   IS NULL OR COST_PER_MINUTE   >= 0),
  COST_PER_HOUR     NUMERIC CHECK (COST_PER_HOUR     IS NULL OR COST_PER_HOUR     >= 0),
  COST_PER_DAY      NUMERIC CHECK (COST_PER_DAY      IS NULL OR COST_PER_DAY      >= 0),
  COST_PER_MONTH    NUMERIC CHECK (COST_PER_MONTH    IS NULL OR COST_PER_MONTH    >= 0),
  COST_PER_YEAR     NUMERIC CHECK (COST_PER_YEAR     IS NULL OR COST_PER_YEAR     >= 0)
);

INSERT INTO USAGE_TIER
(ID, PER_MINUTE, PER_HOUR, PER_DAY, PER_MONTH, PER_YEAR,
 COST_PER_MINUTE, COST_PER_HOUR, COST_PER_DAY, COST_PER_MONTH, COST_PER_YEAR)
VALUES
-- TIER 0 – FREE
('TIER0', 1000, 30000, 200000, 6000000, 6000000 * 12,
 0.00, 0.00, 0.00, 0.00, 0.00),

-- TIER 1 – SANDBOX
('TIER1', 5000, 150000, 1000000, 30000000, 30000000 * 12,
 0.02, 0.50, 1.50, 5, 5 * 12),

-- TIER 2 – DEVELOPER
('TIER2', 25000, 750000, 5000000, 150000000, 150000000 * 12,
 0.10, 2.50, 7.50, 25, 25 * 12),

-- TIER 3 – STARTUP
('TIER3', 125000, 3750000, 25000000, 750000000, 750000000 * 2,
 0.50, 12.50, 37.50, 125, 125 * 12),

-- TIER 4 – BUSINESS
('TIER4', 625000, 18750000, 125000000, 3750000000, 3750000000 * 2,
 2.50, 62.50, 187.50, 625, 625 * 12),

-- TIER 5 – ENTERPRISE
('TIER5', 3125000, 93750000, 625000000, 18750000000, 18750000000 * 2,
 12.50, 312.50, 937.50, 3125, 3125 * 12)
ON CONFLICT (ID) DO NOTHING;

COMMIT;

----------------------------------------
------ USER PROFILES AND PROJECTS ------
----------------------------------------
CREATE TABLE USER_PROFILE (
  USER_ID CHARACTER VARYING(36) PRIMARY KEY NOT NULL,
  EMAIL CHARACTER VARYING(255),
  CREATED_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  NAME CHARACTER VARYING(255),
  TIER_ID VARCHAR(64) NOT NULL DEFAULT 'TIER1' REFERENCES USAGE_TIER (ID)
);

-- CREATE USER PROFILE CREDENTIALS
CREATE TABLE USER_PROFILE_CREDENTIAL (
    USER_ID VARCHAR(36) NOT NULL PRIMARY KEY REFERENCES USER_PROFILE (USER_ID),
    TYPE VARCHAR(255) NOT NULL,
    CREDENTIALS VARCHAR(255) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE USER_PROJECT (
  PROJECT_ID VARCHAR(36) NOT NULL PRIMARY KEY,
  PROJECT_NAME VARCHAR(255) NOT NULL,
  USER_ID VARCHAR(36) NOT NULL REFERENCES USER_PROFILE (USER_ID),
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (USER_ID, PROJECT_NAME)
);

ALTER TABLE USER_PROJECT ADD COLUMN UPDATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX USER_PROJECT_USER_ID_IDX ON USER_PROJECT (USER_ID);

CREATE TABLE WORKFLOW_NODE (
    NODE_ID VARCHAR(36) NOT NULL PRIMARY KEY,
    OBJECT_ID VARCHAR(255) NULL,    -- THE ACTUAL OBJECT ID BASED ON THE IDENTIFIER
    NODE_TYPE VARCHAR(255) NOT NULL,
    NODE_LABEL VARCHAR(255) NULL,
    PROJECT_ID VARCHAR(36) NOT NULL REFERENCES USER_PROJECT (PROJECT_ID),
    POSITION_X INT NULL,
    POSITION_Y INT NULL,
    WIDTH INT NULL,
    HEIGHT INT NULL
);

CREATE TABLE WORKFLOW_EDGE (
    SOURCE_NODE_ID VARCHAR(36) NOT NULL REFERENCES WORKFLOW_NODE (NODE_ID),
    TARGET_NODE_ID VARCHAR(36) NOT NULL REFERENCES  WORKFLOW_NODE (NODE_ID),
    SOURCE_HANDLE VARCHAR(255) NULL,
    TARGET_HANDLE VARCHAR(255) NULL,
    ANIMATED BOOL NOT NULL DEFAULT TRUE,
    EDGE_LABEL VARCHAR(255) NULL,
    TYPE VARCHAR(255) NOT NULL DEFAULT 'DEFAULT',
    PRIMARY KEY (SOURCE_NODE_ID, TARGET_NODE_ID)
);

CREATE TABLE TEMPLATE (
    TEMPLATE_ID VARCHAR(36) NOT NULL PRIMARY KEY,
    TEMPLATE_PATH VARCHAR(255) NOT NULL,
    TEMPLATE_CONTENT TEXT NOT NULL,
    TEMPLATE_TYPE VARCHAR(255) DEFAULT 'USER_TEMPLATE',
    PROJECT_ID VARCHAR(36) NULL REFERENCES USER_PROJECT (PROJECT_ID)
);

CREATE TABLE STATE
(
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    PROJECT_ID VARCHAR(36) NULL REFERENCES USER_PROJECT (PROJECT_ID),
    COUNT INT NOT NULL DEFAULT 0,
    STATE_TYPE VARCHAR(255) NOT NULL DEFAULT 'STATECONFIG'
);

CREATE TABLE STATE_CONFIG (
    STATE_ID VARCHAR(255) NOT NULL REFERENCES STATE(ID),
    ATTRIBUTE VARCHAR(255) NOT NULL,
    DATA TEXT,
    PRIMARY KEY (STATE_ID, ATTRIBUTE)
);

CREATE TABLE STATE_COLUMN_KEY_DEFINITION(
    ID SERIAL NOT NULL PRIMARY KEY,
    STATE_ID VARCHAR(255) NOT NULL REFERENCES STATE (ID),
    NAME VARCHAR(255) NOT NULL,
    ALIAS VARCHAR(255),
    REQUIRED BOOL DEFAULT FALSE,
    CALLABLE BOOL DEFAULT FALSE,
    DEFINITION_TYPE VARCHAR(255) NOT NULL
);

CREATE TABLE STATE_COLUMN (
    ID SERIAL NOT NULL PRIMARY KEY,
    STATE_ID VARCHAR(36) NOT NULL REFERENCES STATE(ID),
    NAME VARCHAR(255) NOT NULL,
    DATA_TYPE VARCHAR(64) DEFAULT 'STR',
    REQUIRED BOOLEAN DEFAULT TRUE,
    CALLABLE BOOLEAN DEFAULT FALSE,
    MIN_LENGTH INT DEFAULT 0,
    MAX_LENGTH INT DEFAULT 255,
    DIMENSIONS INT DEFAULT 384,
    VALUE VARCHAR(255),
    SOURCE_COLUMN_NAME VARCHAR(255)
);

ALTER TABLE STATE_COLUMN ADD COLUMN DISPLAY_ORDER INT DEFAULT 0;
CREATE UNIQUE INDEX STATE_COLUMN_UNIQUE_KEY ON STATE_COLUMN (ID, STATE_ID);
CREATE UNIQUE INDEX STATE_COLUMN_STATE_NAME_UX ON STATE_COLUMN (STATE_ID, NAME);

CREATE TABLE STATE_COLUMN_DATA
(
    COLUMN_ID BIGINT NOT NULL REFERENCES STATE_COLUMN (ID),
    DATA_INDEX BIGINT NOT NULL,
    DATA_VALUE TEXT
);

CREATE TABLE STATE_COLUMN_DATA_MAPPING (
    STATE_ID VARCHAR(36) NOT NULL,
    STATE_KEY VARCHAR(255) NOT NULL,
    DATA_INDEX BIGINT NOT NULL,
    PRIMARY KEY (STATE_ID, STATE_KEY, DATA_INDEX)
);

CREATE TABLE PROCESSOR_CLASS (
    CLASS_NAME VARCHAR(32) NOT NULL PRIMARY KEY
);

INSERT INTO PROCESSOR_CLASS VALUES
    ('CODEPROCESSING'),
    ('NATURALLANGUAGEPROCESSING'),
    ('IMAGEPROCESSING'),
    ('DATATRANSFORMATION'),
    ('TEXTPROCESSING'),
    ('VIDEOPROCESSING'),
    ('AUDIOPROCESSING'),
    ('DATAANALYSIS'),
    ('SIGNALPROCESSING'),
    ('MACHINELEARNING'),
    ('DATABASEPROCESSING'),
    ('INTERACTION'),
    ('PROPRIETARY')
    ON CONFLICT DO NOTHING;

COMMIT;

CREATE TABLE PROCESSOR_PROVIDER (
    ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(512) NOT NULL,
    VERSION VARCHAR(256) NOT NULL,
    CLASS_NAME VARCHAR(256) NOT NULL REFERENCES PROCESSOR_CLASS (CLASS_NAME),
    USER_ID VARCHAR(36) NULL REFERENCES USER_PROFILE (USER_ID),
    PROJECT_ID VARCHAR(36) NULL REFERENCES USER_PROJECT (PROJECT_ID)
);

ALTER TABLE PROCESSOR_PROVIDER ADD COLUMN ROUTE JSONB NULL;
ALTER TABLE PROCESSOR_PROVIDER ADD COLUMN CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE PROCESSOR_PROVIDER ADD COLUMN UPDATED_DATE TIMESTAMP NULL DEFAULT NULL;

INSERT INTO PROCESSOR_PROVIDER (ID, NAME, VERSION, CLASS_NAME) VALUES
 --- GPT 4O
    ('LANGUAGE/MODELS/OPENAI/GPT-4O', 'OPENAI', 'GPT-4O', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENAI/GPT-4O-MINI', 'OPENAI', 'GPT-4O-MINI', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENAI/GPT-4O-2024-05-13', 'OPENAI', 'GPT-4O-2024-05-13', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENAI/GPT-4O-2024-08-06', 'OPENAI', 'GPT-4O-2024-08-06', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENAI/GPT-4O-2024-11-20', 'OPENAI', 'GPT-4O-2024-11-20', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENAI/GPT-4O-LATEST', 'OPENAI', 'CHATGPT-4O-LATEST', 'NATURALLANGUAGEPROCESSING'),

 --- GPT 4.1
    ('LANGUAGE/MODELS/OPENAI/GPT-4.1', 'OPENAI', 'GPT-4.1', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENAI/GPT-4.1-MINI', 'OPENAI', 'GPT-4.1-MINI', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENAI/GPT-4.1-NANO', 'OPENAI', 'GPT-4.1-NANO', 'NATURALLANGUAGEPROCESSING'),


--- GPT 5
    ('LANGUAGE/MODELS/OPENAI/GPT-5', 'OPENAI', 'GPT-5', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENAI/GPT-5-CHAT-LATEST', 'OPENAI', 'GPT-5-CHAT-LATEST', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENAI/GPT-5-MINI', 'OPENAI', 'GPT-5-MINI', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENAI/GPT-5-NANO', 'OPENAI', 'GPT-5-NANO', 'NATURALLANGUAGEPROCESSING'),

--- OTHER OPENAI
    ('LANGUAGE/MODELS/OPENAI/O1-PREVIEW', 'OPENAI', 'O1-PREVIEW', 'NATURALLANGUAGEPROCESSING'),
    ('IMAGE/MODELS/OPENAI/DALL-E-2', 'OPENAI', 'DALL-E-2', 'IMAGEPROCESSING'),
    ('IMAGE/MODELS/OPENAI/DALL-E-3', 'OPENAI', 'DALL-E-3', 'IMAGEPROCESSING'),

-- OPENROUTER
    ('LANGUAGE/MODELS/OPENROUTER/OPENAI/GPT-4.1', 'OPENROUTER', 'OPENAI/GPT-4.1', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/OPENAI/GPT-4.1-MINI', 'OPENROUTER', 'OPENAI/GPT-4.1-MINI', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/OPENAI/GPT-4.1-NANO', 'OPENROUTER', 'OPENAI/GPT-4.1-NANO', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/OPENAI/GPT-4', 'OPENROUTER', 'OPENAI/GPT-4', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/OPENAI/GPT-4O', 'OPENROUTER', 'OPENAI/GPT-4O', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/OPENAI/GPT-4-TURBO', 'OPENROUTER', 'OPENAI/GPT-4-TURBO', 'NATURALLANGUAGEPROCESSING'),

    ('LANGUAGE/MODELS/OPENROUTER/OPENAI/GPT-5', 'OPENROUTER', 'OPENAI/GPT-5', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/OPENAI/GPT-5-MINI', 'OPENROUTER', 'OPENAI/GPT-5-MINI', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/OPENAI/GPT-5-CODEX', 'OPENROUTER', 'OPENAI/GPT-5-CODEX', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/OPENAI/GPT-5-CHAT', 'OPENROUTER', 'OPENAI/GPT-5-CHAT', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/OPENAI/GPT-5-NANO', 'OPENROUTER', 'OPENAI/GPT-5-NANO', 'NATURALLANGUAGEPROCESSING'),

    ('LANGUAGE/MODELS/OPENROUTER/GOOGLE/GEMINI-2.5-FLASH', 'OPENROUTER', 'GOOGLE/GEMINI-2.5-FLASH', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/GOOGLE/GEMINI-2.5-PRO', 'OPENROUTER', 'GOOGLE/GEMINI-2.5-PRO', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/GOOGLE/GEMINI-2.5-FLASH-LITE', 'OPENROUTER', 'GOOGLE/GEMINI-2.5-FLASH-LITE', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/GOOGLE/GEMINI-PRO-1.5', 'OPENROUTER', 'GOOGLE/GEMINI-PRO-1.5', 'NATURALLANGUAGEPROCESSING'),

    ('LANGUAGE/MODELS/OPENROUTER/X-AI/GROK-4', 'OPENROUTER', 'X-AI/GROK-4', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/X-AI/GROK-4-FAST', 'OPENROUTER', 'X-AI/GROK-4-FAST', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/X-AI/GROK-3', 'OPENROUTER', 'X-AI/GROK-3', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/X-AI/GROK-3-MINI', 'OPENROUTER', 'X-AI/GROK-3-MINI', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/X-AI/GROK-2', 'OPENROUTER', 'X-AI/GROK-2', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/X-AI/GROK-2-MINI', 'OPENROUTER', 'X-AI/GROK-2-MINI', 'NATURALLANGUAGEPROCESSING'),

    ('LANGUAGE/MODELS/OPENROUTER/MOONSHOTAI/KIMI-K2', 'OPENROUTER', 'MOONSHOTAI/KIMI-K2', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/ANTHROPIC/CLAUDE-3-OPUS', 'OPENROUTER', 'ANTHROPIC/CLAUDE-3-OPUS', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/ANTHROPIC/CLAUDE-OPUS-4', 'OPENROUTER', 'ANTHROPIC/CLAUDE-OPUS-4', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/ANTHROPIC/CLAUDE-OPUS-4.1', 'OPENROUTER', 'ANTHROPIC/CLAUDE-OPUS-4.1', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/ANTHROPIC/CLAUDE-SONNET-4.5', 'OPENROUTER', 'ANTHROPIC/CLAUDE-SONNET-4.5', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/ANTHROPIC/CLAUDE-SONNET-4', 'OPENROUTER', 'ANTHROPIC/CLAUDE-SONNET-4', 'NATURALLANGUAGEPROCESSING'),

    ('LANGUAGE/MODELS/OPENROUTER/ANTHROPIC/CLAUDE-3-SONNET', 'OPENROUTER', 'ANTHROPIC/CLAUDE-3-SONNET', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/ANTHROPIC/CLAUDE-3.5-SONNET', 'OPENROUTER', 'ANTHROPIC/CLAUDE-3.5-SONNET', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/ANTHROPIC/CLAUDE-3.7-SONNET', 'OPENROUTER', 'ANTHROPIC/CLAUDE-3.7-SONNET', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/ANTHROPIC/CLAUDE-3.7-SONNET:THINKING', 'OPENROUTER', 'ANTHROPIC/CLAUDE-3.7-SONNET:THINKING', 'NATURALLANGUAGEPROCESSING'),



    ('LANGUAGE/MODELS/OPENROUTER/MISTRALAI/MISTRAL-NEMO', 'OPENROUTER', 'MISTRALAI/MISTRAL-NEMO', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/MISTRALAI/MISTRAL-TINY', 'OPENROUTER', 'MISTRALAI/MISTRAL-TINY', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/MISTRALAI/MISTRAL-SMALL-3.2-24B-INSTRUCT', 'OPENROUTER', 'MISTRALAI/MISTRAL-SMALL-3.2-24B-INSTRUCT', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/MISTRALAI/MISTRAL-SMALL', 'OPENROUTER', 'MISTRALAI/MISTRAL-SMALL', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/MISTRALAI/MISTRAL-MEDIUM-3.1', 'OPENROUTER', 'MISTRALAI/MISTRAL-MEDIUM-3.1', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/MISTRALAI/MISTRAL-LARGE', 'OPENROUTER', 'MISTRALAI/MISTRAL-LARGE', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/MISTRALAI/MISTRAL-LARGE-2411', 'OPENROUTER', 'MISTRALAI/MISTRAL-LARGE-2411', 'NATURALLANGUAGEPROCESSING'),

    ('LANGUAGE/MODELS/OPENROUTER/MISTRALAI/MAGISTRAL-SMALL-2506', 'OPENROUTER', 'MISTRALAI/MAGISTRAL-SMALL-2506', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/MISTRALAI/MAGISTRAL-MEDIUM-2506', 'OPENROUTER', 'MISTRALAI/MAGISTRAL-MEDIUM-2506', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/MISTRALAI/MAGISTRAL-MEDIUM-2506:THINKING', 'OPENROUTER', 'MISTRALAI/MAGISTRAL-MEDIUM-2506:THINKING', 'NATURALLANGUAGEPROCESSING'),


    ('LANGUAGE/MODELS/OPENROUTER/DEEPSEEK/DEEPSEEK-R1', 'OPENROUTER', 'DEEPSEEK/DEEPSEEK-R1', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/DEEPSEEK/DEEPSEEK-R1-DISTILL-LLAMA-70B', 'OPENROUTER', 'DEEPSEEK/DEEPSEEK-R1-DISTILL-LLAMA-70B', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/MDEEPSEEK/DEEPSEEK-R1-0528-QWEN3-8B', 'OPENROUTER', 'DEEPSEEK/DEEPSEEK-R1-0528-QWEN3-8B', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/DEEPSEEK/DEEPSEEK-R1-DISTILL-QWEN-32B', 'OPENROUTER', 'DEEPSEEK/DEEPSEEK-R1-DISTILL-QWEN-32B', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/DEEPSEEK/DEEPSEEK-CHAT-V3.1', 'OPENROUTER', 'DEEPSEEK/DEEPSEEK-CHAT-V3.1', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/DEEPSEEK/DEEPSEEK-V3.1-TERMINUS', 'OPENROUTER', 'DEEPSEEK/DEEPSEEK-V3.1-TERMINUS', 'NATURALLANGUAGEPROCESSING'),

    ('LANGUAGE/MODELS/OPENROUTER/META-LLAMA/LLAMA-4-SCOUT', 'OPENROUTER', 'META-LLAMA/LLAMA-4-SCOUT', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/META-LLAMA/LLAMA-4-MAVERICK', 'OPENROUTER', 'META-LLAMA/LLAMA-4-MAVERICK', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/META-LLAMA/LLAMA-3.1-405B-INSTRUCT', 'OPENROUTER', 'META-LLAMA/LLAMA-3.1-405B-INSTRUCT', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/NVIDIA/LLAMA-3.3-NEMOTRON-SUPER-49B-V1', 'OPENROUTER', 'NVIDIA/LLAMA-3.3-NEMOTRON-SUPER-49B-V1', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/META-LLAMA/CODELLAMA-34B-INSTRUCT', 'OPENROUTER', 'META-LLAMA/CODELLAMA-34B-INSTRUCT', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/OPENROUTER/META-LLAMA/LLAMA-GUARD-4-12B', 'OPENROUTER', 'META-LLAMA/LLAMA-GUARD-4-12B', 'NATURALLANGUAGEPROCESSING'),

-- OTHERS
    ('LANGUAGE/MODELS/LLAMA/LLAMA3.1-8B', 'LLAMA', 'LLAMA3.1-8B', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/LLAMA/LLAMA3.1-705B', 'LLAMA', 'LLAMA3.1-70B', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/LLAMA/LLAMA3.1-405B', 'LLAMA', 'LLAMA3.1-405B', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/GOOGLE/GEMINI-1.5-FLASH', 'GOOGLE', 'GEMINI-1.5-FLASH', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/GOOGLE/GEMINI-1.5-PRO-001', 'GOOGLE', 'GEMINI-1.5-PRO-001', 'NATURALLANGUAGEPROCESSING'),

-- ANTHROPIC
    ('LANGUAGE/MODELS/ANTHROPIC/CLAUDE-2.0', 'ANTHROPIC', 'CLAUDE-2', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/ANTHROPIC/CLAUDE-2.1', 'ANTHROPIC', 'CLAUDE-2.1', 'NATURALLANGUAGEPROCESSING'),

    ('LANGUAGE/MODELS/ANTHROPIC/CLAUDE-3-OPUS-LATEST', 'ANTHROPIC', 'CLAUDE-3-OPUS-LATEST', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/ANTHROPIC/CLAUDE-3-OPUS-20240229', 'ANTHROPIC', 'CLAUDE-3-OPUS-20240229', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/ANTHROPIC/CLAUDE-4.0-OPUS-LATEST', 'ANTHROPIC', 'CLAUDE-OPUS-4-0', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/ANTHROPIC/CLAUDE-4.1-OPUS-LATEST', 'ANTHROPIC', 'CLAUDE-OPUS-4-1', 'NATURALLANGUAGEPROCESSING'),

    ('LANGUAGE/MODELS/ANTHROPIC/CLAUDE-3-5-SONNET-LATEST', 'ANTHROPIC', 'CLAUDE-3-5-SONNET-LATEST', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/ANTHROPIC/CLAUDE-3-5-SONNET-20240620', 'ANTHROPIC', 'CLAUDE-3-5-SONNET-20240620', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/ANTHROPIC/CLAUDE-3-5-SONNET-20241022', 'ANTHROPIC', 'CLAUDE-3-5-SONNET-20241022', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/ANTHROPIC/CLAUDE-3-7-SONNET-LATEST', 'ANTHROPIC', 'CLAUDE-3-7-SONNET-LATEST', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/ANTHROPIC/CLAUDE-4.0-SONNET-LATEST', 'ANTHROPIC', 'CLAUDE-SONNET-4-0', 'NATURALLANGUAGEPROCESSING'),

    ('LANGUAGE/MODELS/ANTHROPIC/CLAUDE-3-5-HAIKU-LATEST', 'ANTHROPIC', 'CLAUDE-3-5-HAIKU-LATEST', 'NATURALLANGUAGEPROCESSING'),
    ('LANGUAGE/MODELS/ANTHROPIC/CLAUDE-3-5-HAIKU-20241022', 'ANTHROPIC', 'CLAUDE-3-5-HAIKU-20241022', 'NATURALLANGUAGEPROCESSING'),

    -- MIXERS
    ('DATA/TRANSFORMERS/MIXER/STATE-ONLINE-JOIN-1.0', 'STATE ONLINE JOIN', 'STATE-ONLINE-JOIN-1.0', 'DATATRANSFORMATION'),
    ('DATA/TRANSFORMERS/MIXER/STATE-ONLINE-MERGE-1.0', 'STATE ONLINE MERGE', 'STATE-ONLINE-MERGE-1.0', 'DATATRANSFORMATION'),
    ('DATA/TRANSFORMERS/MIXER/STATE-ONLINE-CROSS-JOIN-1.0', 'STATE ONLINE CROSS JOIN', 'STATE-ONLINE-CROSS-JOIN-1.0', 'DATATRANSFORMATION'),
    ('DATA/TRANSFORMERS/MIXER/STATE-TABLES-1.0', 'STATE TABLES', 'STATE-TABLES-1.0', 'DATATRANSFORMATION'),
    ('DATA/TRANSFORMERS/SAMPLER/STATE-SAMPLE-MULTIPLIER-1.0', 'STATE SAMPLE MULTIPLIER', 'STATE-SAMPLE-MULTIPLIER-1.0', 'DATATRANSFORMATION'),

    -- DATA SOURCE
    ('DATA/SOURCE/SQL-1.0', 'SQL', 'SQL-1.0', 'DATABASEPROCESSING'),

    -- CODE EXECUTORS
    ('CODE/EXECUTOR/PYTHON/PYTHON-EXECUTOR-1.0', 'PYTHON EXECUTOR', 'PYTHON-EXECUTOR-1.0', 'CODEPROCESSING'),
    ('CODE/EXECUTOR/MAKO/MAKO-EXECUTOR-1.0', 'MAKO EXECUTOR', 'MAKO-EXECUTOR-1.0', 'CODEPROCESSING'),

    --- USER INTERACTIONS
    ('INTERACTION/USER/USER-INTERACTION', 'USER INTERACTION', 'USER-INTERACTION-1.0', 'INTERACTION')
ON CONFLICT (ID) DO UPDATE SET
    NAME=EXCLUDED.NAME,
    VERSION=EXCLUDED.VERSION,
    CLASS_NAME=EXCLUDED.CLASS_NAME;

CREATE TYPE PROCESSOR_STATUS AS ENUM (
       'CREATED', 'ROUTE', 'ROUTED',
       'QUEUED', 'RUNNING', 'COMPLETED',
       'TERMINATE', 'STOPPED', 'FAILED'
);

CREATE TABLE PROCESSOR (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    PROVIDER_ID VARCHAR(255) NULL REFERENCES PROCESSOR_PROVIDER (ID),
    PROJECT_ID VARCHAR(36) NOT NULL REFERENCES USER_PROJECT (PROJECT_ID),
    STATUS PROCESSOR_STATUS NOT NULL
);

ALTER TABLE PROCESSOR ADD COLUMN PROPERTIES JSONB NULL;
ALTER TABLE PROCESSOR ADD COLUMN NAME VARCHAR(255) NULL;
ALTER TABLE PROCESSOR ADD COLUMN CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE PROCESSOR ADD COLUMN UPDATED_DATE TIMESTAMP NULL DEFAULT NULL;

CREATE TYPE PROCESSOR_STATE_DIRECTION AS ENUM (
       'INPUT', 'OUTPUT'
);

CREATE TABLE PROCESSOR_STATE (
    ID VARCHAR(73) NOT NULL,
    INTERNAL_ID SERIAL NOT NULL,
    PROCESSOR_ID VARCHAR(36) NOT NULL,
    STATE_ID VARCHAR(36) NOT NULL REFERENCES STATE (ID),
    DIRECTION PROCESSOR_STATE_DIRECTION NOT NULL,
    STATUS PROCESSOR_STATUS NOT NULL,
    COUNT INT NULL,
    CURRENT_INDEX INT NULL,
    MAXIMUM_INDEX INT NULL,
    PRIMARY KEY (PROCESSOR_ID, STATE_ID, DIRECTION),
    UNIQUE (INTERNAL_ID),
    UNIQUE (ID)
);

ALTER TABLE PROCESSOR_STATE ADD CONSTRAINT PROCESSOR_STATE_STATE_ID_FK FOREIGN KEY (STATE_ID) REFERENCES STATE(ID);
ALTER TABLE PROCESSOR_STATE ADD CONSTRAINT PROCESSOR_STATE_PROCESSOR_ID_FK FOREIGN KEY (PROCESSOR_ID) REFERENCES PROCESSOR(ID);
COMMIT;

-- CREATE TABLE IF NOT EXISTS TRACE
-- (
--     ID SERIAL NOT NULL PRIMARY KEY,
--     PARTITION   VARCHAR(128)                            NOT NULL,
--     REFERENCE   VARCHAR(128)                            NOT NULL,
--     ACTION      VARCHAR(255)                            NOT NULL,
--     ACTION_TIME TIMESTAMP   DEFAULT CURRENT_TIMESTAMP   NOT NULL,
--     LEVEL       TRACE_LEVEL DEFAULT 'INFO'::TRACE_LEVEL NOT NULL,
--     MESSAGE     TEXT
-- );

CREATE TABLE MONITOR_LOG_EVENT (
    LOG_ID SERIAL NOT NULL PRIMARY KEY,
    LOG_TYPE VARCHAR(255) NOT NULL, -- TODO SHOULD BE AN ENUM OF TYPE LOG_TYPE
    LOG_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INTERNAL_REFERENCE_ID INT NULL, -- AN INTERNAL ID DEPENDING ON WHAT IS BEING MONITORED, E.G. A PROCESSOR_STATE INTERNAL_ID
    USER_ID VARCHAR(36) NULL,       -- THIS IS USEFUL WHEN PROCESSOR_STATE_ID IS NOT DEFINED
    PROJECT_ID VARCHAR(36) NULL,    -- THIS IS USEFUL WHEN PROCESSOR_STATE_ID IS NOT DEFINED
    EXCEPTION TEXT NULL,
    DATA TEXT NULL
);

CREATE OR REPLACE VIEW STATE_COLUMN_DATA_VIEW
AS
SELECT SC.*, SD.* FROM STATE_COLUMN SC
 LEFT OUTER JOIN STATE_COLUMN_DATA SD
   ON SC.ID = SD.COLUMN_ID
ORDER BY STATE_ID, DATA_INDEX, COLUMN_ID;

--- VALIDATION FUNCTION FOR COLUMN ID
CREATE OR REPLACE FUNCTION VALIDATE_COLUMN_ID(NEW_ID BIGINT, NEW_STATE_ID VARCHAR)
RETURNS BIGINT AS $$
DECLARE
    RESULT BIGINT;
BEGIN
    IF NEW_ID IS NOT NULL THEN
        -- CHECK IF THE PROVIDED ID EXISTS WITH THE GIVEN STATE_ID
        IF EXISTS (SELECT 1 FROM STATE_COLUMN WHERE ID = NEW_ID AND STATE_ID = NEW_STATE_ID) THEN
            RESULT := NEW_ID;
        -- CHECK IF THE PROVIDED ID EXISTS WITH A DIFFERENT STATE_ID
        ELSIF EXISTS (SELECT 1 FROM STATE_COLUMN WHERE ID = NEW_ID) THEN
            RAISE EXCEPTION 'ILLEGAL ID: THE PROVIDED ID ALREADY EXISTS WITH A DIFFERENT STATE_ID';
        ELSE
            RESULT := NULL;
        END IF;
    ELSE
        RESULT := NULL;
    END IF;

    RETURN RESULT;
END;
$$ LANGUAGE PLPGSQL;


-- AUTO-GENERATED DEFINITION
CREATE TYPE USAGE_UNIT_TYPE AS ENUM ('TOKEN', 'COMPUTE');
CREATE TYPE USAGE_UNIT_SUBTYPE AS ENUM ('INPUT', 'OUTPUT');

CREATE TABLE IF NOT EXISTS USAGE
(
    ID               SERIAL PRIMARY KEY,
    TRANSACTION_TIME TIMESTAMP,
    PROJECT_ID       VARCHAR(36)        NOT NULL REFERENCES PUBLIC.USER_PROJECT,
    RESOURCE_ID      VARCHAR(255)       NOT NULL,
    RESOURCE_TYPE    VARCHAR(255)       NOT NULL,
    UNIT_TYPE        USAGE_UNIT_TYPE    NOT NULL,
    UNIT_SUBTYPE     USAGE_UNIT_SUBTYPE NOT NULL,
    UNIT_COUNT       INTEGER DEFAULT 0  NOT NULL,
    METADATA         TEXT
);

CREATE INDEX USAGE_PROJECT_IDX ON USAGE (PROJECT_ID);
CREATE INDEX USAGE_PROJECT_TIME_IDX ON USAGE (PROJECT_ID, TRANSACTION_TIME);

------------------------------------------------------------------
-- SESSION AND SESSION MESSAGES FOR TRACKING USER INTERACTIONS
------------------------------------------------------------------
CREATE TABLE SESSION (
    SESSION_ID VARCHAR(36) NOT NULL PRIMARY KEY,
    CREATED_DATE    TIMESTAMP NOT NULL,
    OWNER_USER_ID   VARCHAR(36) NOT NULL REFERENCES USER_PROFILE (USER_ID)
);

CREATE TABLE SESSION_MESSAGE (
    MESSAGE_ID SERIAL NOT NULL PRIMARY KEY,
    SESSION_ID VARCHAR(36) NOT NULL REFERENCES SESSION (SESSION_ID),
    USER_ID VARCHAR(36) NOT NULL REFERENCES USER_PROFILE (USER_ID),
    ORIGINAL_CONTENT TEXT NULL,
    EXECUTED_CONTENT TEXT NULL,
    MESSAGE_DATE TIMESTAMP NOT NULL
);

CREATE TYPE USER_SESSION_ACCESS_LEVEL AS ENUM ('DEFAULT', 'ADMIN');

CREATE TABLE USER_SESSION_ACCESS (
    USER_ID VARCHAR(36) NOT NULL REFERENCES USER_PROFILE (USER_ID),
    SESSION_ID VARCHAR(36) NOT NULL REFERENCES SESSION (SESSION_ID),
    ACCESS_LEVEL USER_SESSION_ACCESS_LEVEL NOT NULL DEFAULT 'DEFAULT',
    ACCESS_DATE TIMESTAMP NOT NULL
);


-- DEFINE ENUM FOR CONFIGURATION TYPES
CREATE TYPE CONFIG_TYPE AS ENUM ('SECRET', 'CONFIG_MAP');

-- TABLE TO MANAGE ENCRYPTION KEY PROVIDERS
CREATE TABLE VAULT (
    ID VARCHAR(36) PRIMARY KEY, -- UNIQUE IDENTIFIER FOR THE PROVIDER
    NAME VARCHAR(255) NOT NULL UNIQUE, -- PROVIDER NAME (E.G., AWS KMS, HASHICORP VAULT)
    TYPE VARCHAR(50) NOT NULL, -- PROVIDER TYPE (E.G., 'KMS', 'VAULT', 'LOCAL')
    METADATA JSONB, -- ADDITIONAL METADATA FOR THE PROVIDER (E.G., REGION, ENDPOINT)
    CREATED_DATE TIMESTAMP DEFAULT NOW(),
    UPDATED_DATE TIMESTAMP DEFAULT NOW()
);

CREATE TABLE CONFIG_MAP (
    ID VARCHAR(36) PRIMARY KEY, -- USE UUID FOR UNIQUE IDENTIFIERS
    NAME VARCHAR(255) NOT NULL, -- DESCRIPTIVE NAME FOR THE CONFIGURATION
    TYPE CONFIG_TYPE NOT NULL, -- ENUM FOR 'SECRET' OR 'CONFIG_MAP'
    DATA JSONB NOT NULL, -- CONFIGURATION DATA (ENCRYPTED OR PLAINTEXT)
    VAULT_KEY_ID VARCHAR(255), -- ID OF THE ENCRYPTION KEY (NULLABLE)
    VAULT_ID VARCHAR(36) REFERENCES VAULT (ID), -- REFERENCE TO ENCRYPTION KEY PROVIDER
    OWNER_ID VARCHAR(36), -- OPTIONAL: OWNERSHIP FOR MULTI-TENANCY
    CREATED_DATE TIMESTAMP DEFAULT NOW(),
    UPDATED_DATE TIMESTAMP DEFAULT NOW(),
    DELETED_DATE TIMESTAMP -- OPTIONAL: SOFT DELETE SUPPORT
);

-- INDEX FOR JSONB DATA TO OPTIMIZE QUERIES
CREATE INDEX IDX_CONFIGURATION_DATA ON CONFIG_MAP USING GIN(DATA JSONB_PATH_OPS);

-- INDEX FOR FILTERING BY TYPE (OPTIONAL OPTIMIZATION)
CREATE INDEX IDX_CONFIGURATION_TYPE ON CONFIG_MAP(TYPE);

-- TABLE FOR FILTERS
CREATE TABLE FILTER (
    ID VARCHAR(255) PRIMARY KEY, -- UNIQUE IDENTIFIER FOR THE FILTER
    NAME VARCHAR(255), -- FILTER NAME
    USER_ID VARCHAR(36) NOT NULL REFERENCES USER_PROFILE(USER_ID), -- OWNER OF THE FILTER
    FILTER_ITEMS JSONB NOT NULL DEFAULT '{}', -- FILTER ITEMS STORED AS JSON
    CREATED_DATE TIMESTAMP DEFAULT NOW(),
    UPDATED_DATE TIMESTAMP DEFAULT NOW()
);

-- INDEX FOR USER_ID TO OPTIMIZE QUERIES BY USER
CREATE INDEX IDX_FILTER_USER_ID ON FILTER(USER_ID);

-- INDEX FOR JSONB FILTER_ITEMS TO OPTIMIZE QUERIES
CREATE INDEX IDX_FILTER_ITEMS ON FILTER USING GIN(FILTER_ITEMS JSONB_PATH_OPS);

CREATE INDEX PROCESSOR_STATE_PROCESSOR_DIRECTION_IDX ON PROCESSOR_STATE (PROCESSOR_ID, DIRECTION);
CREATE INDEX PROCESSOR_STATE_STATE_DIRECTION_IDX ON PROCESSOR_STATE (STATE_ID, DIRECTION);
CREATE INDEX PROCESSOR_STATE_PROCESSOR ON PROCESSOR_STATE (PROCESSOR_ID);
CREATE INDEX PROCESSOR_STATE_STATE ON PROCESSOR_STATE (STATE_ID);

CREATE INDEX STATE_PROJECT_IDX ON STATE (PROJECT_ID);
CREATE INDEX PROCESSOR_PROJECT_IDX ON PROCESSOR (PROJECT_ID);
CREATE INDEX STATE_COLUMN_STATE_IDX ON STATE_COLUMN (STATE_ID);

CREATE INDEX STATE_CONFIG_STATE_IDX ON STATE_CONFIG (STATE_ID);
CREATE INDEX TEMPLATE_PROJECT_IDX ON TEMPLATE (PROJECT_ID);
CREATE INDEX WORKFLOW_NODE_PROJECT_IDX ON WORKFLOW_NODE (PROJECT_ID);
CREATE INDEX STATE_COLUMN_KEY_DEFINITION_STATE_IDX ON STATE_COLUMN_KEY_DEFINITION (STATE_ID);
CREATE UNIQUE INDEX STATE_COLUMN_KEY_DEFINITION_STATE_NAME_TYPE_IDX ON STATE_COLUMN_KEY_DEFINITION (STATE_ID, NAME, DEFINITION_TYPE);
CREATE INDEX STATE_COLUMN_DATA_MAPPING_STATE_IDX ON STATE_COLUMN_DATA_MAPPING (STATE_ID);
CREATE INDEX MONITOR_LOG_EVENT_USER_ID ON MONITOR_LOG_EVENT (USER_ID);
CREATE INDEX MONITOR_LOG_EVENT_PROJECT_ID ON MONITOR_LOG_EVENT (PROJECT_ID);
CREATE INDEX MONITOR_LOG_EVENT_USER_AND_PROJECT_ID ON MONITOR_LOG_EVENT (USER_ID, PROJECT_ID);

-- CREATE UNIQUE INDEX
CREATE EXTENSION IF NOT EXISTS PG_TRGM;

CREATE UNIQUE INDEX IF NOT EXISTS STATE_COLUMN_DATA_COMP_UX
    ON PUBLIC.STATE_COLUMN_DATA (COLUMN_ID, DATA_INDEX);
CREATE INDEX STATE_COLUMN_DATA_COLUMN_IDX
    ON PUBLIC.STATE_COLUMN_DATA (COLUMN_ID);
CREATE INDEX STATE_COLUMN_DATA_TRGM_IDX
    ON PUBLIC.STATE_COLUMN_DATA USING GIN (DATA_VALUE PUBLIC.GIN_TRGM_OPS);


-- CREATE ENUM TYPE FOR ACTION_TYPE
CREATE TYPE ACTION_TYPE_ENUM AS ENUM ('SLIDER', 'TEXT', 'YES/NO', 'DROPDOWN');

-- CREATE THE MAIN TABLE
CREATE TABLE STATE_ACTION_DEFINITION (
    ID VARCHAR(36) PRIMARY KEY, -- AUTOMATICALLY GENERATE A UUID IF NOT PROVIDED
    STATE_ID VARCHAR(36) NOT NULL,                       -- FOREIGN KEY, IF NEEDED, CAN BE DEFINED HERE
    ACTION_TYPE ACTION_TYPE_ENUM NOT NULL,       -- ENUM TYPE FOR ACTION TYPE
    FIELD VARCHAR(255) NOT NULL,                 -- OPTIONAL FIELD NAME
    REMOTE_URL VARCHAR(4000) DEFAULT NULL,            -- DEFAULTS TO FALSE IF NOT PROVIDED
    FIELD_OPTIONS JSON NOT NULL,                -- FIELD OPTIONS AS RAW JSON
    CREATED_DATE TIMESTAMPTZ DEFAULT NOW()        -- AUTOMATICALLY SET TO CURRENT TIMESTAMP
);
CREATE INDEX STATE_ACTION_DEFINITION_STATE_IDX ON STATE_ACTION_DEFINITION (STATE_ID);