-- ===========================
-- CLEANUP OLD DEFINITIONS
-- ===========================

-- DROP OLD TRIGGERS, FUNCTIONS, AND TABLE
DROP TRIGGER IF EXISTS TRG_USAGE_ROLLUP_INS ON USAGE;
DROP TRIGGER IF EXISTS TRG_USAGE_ROLLUP_UPD ON USAGE;
DROP TRIGGER IF EXISTS TRG_USAGE_ROLLUP_DEL ON USAGE;

DROP FUNCTION IF EXISTS USAGE_ROLLUP_TRG() CASCADE;
DROP FUNCTION IF EXISTS _USAGE_ROLLUP_APPLY(
    TIMESTAMPTZ, VARCHAR, VARCHAR, VARCHAR, VARCHAR,
    USAGE_UNIT_TYPE, USAGE_UNIT_SUBTYPE, INTEGER
) CASCADE;

DROP TABLE IF EXISTS USAGE_MINUTE_ROLLUP CASCADE;

-- ===========================
-- RECREATE FRESH DEFINITIONS
-- ===========================

CREATE TABLE USAGE_MINUTE_ROLLUP (
    BUCKET_UTC     TIMESTAMPTZ       NOT NULL,
    USER_ID        VARCHAR(36)       NOT NULL,
    PROJECT_ID     VARCHAR(36)       NOT NULL,
    RESOURCE_ID    VARCHAR(255)      NOT NULL,
    RESOURCE_TYPE  VARCHAR(255)      NOT NULL,
    UNIT_TYPE      USAGE_UNIT_TYPE   NOT NULL,
    UNIT_SUBTYPE   USAGE_UNIT_SUBTYPE NOT NULL,
    UNIT_COUNT     BIGINT           NOT NULL DEFAULT 0,
    CALL_COUNT     BIGINT           NOT NULL DEFAULT 0,
    PRIMARY KEY (BUCKET_UTC, USER_ID, PROJECT_ID, RESOURCE_ID, RESOURCE_TYPE, UNIT_TYPE, UNIT_SUBTYPE)
);

CREATE INDEX USAGE_MINUTE_ROLLUP_PROJ_TIME ON USAGE_MINUTE_ROLLUP (PROJECT_ID, BUCKET_UTC);
CREATE INDEX USAGE_MINUTE_ROLLUP_USER_TIME ON USAGE_MINUTE_ROLLUP (USER_ID, BUCKET_UTC);


CREATE OR REPLACE FUNCTION _USAGE_ROLLUP_APPLY(
    P_BUCKET     TIMESTAMPTZ,
    P_USER       VARCHAR(36),
    P_PROJ       VARCHAR(36),
    P_RES        VARCHAR(255),
    P_RTYPE      VARCHAR(255),
    P_UTYPE      USAGE_UNIT_TYPE,
    P_USUBTYPE   USAGE_UNIT_SUBTYPE,
    P_DELTA      BIGINT,
    P_CALL       BIGINT
) RETURNS VOID LANGUAGE PLPGSQL AS $$
BEGIN
    INSERT INTO USAGE_MINUTE_ROLLUP (
        BUCKET_UTC,
        USER_ID,
        PROJECT_ID,
        RESOURCE_ID,
        RESOURCE_TYPE,
        UNIT_TYPE,
        UNIT_SUBTYPE,
        UNIT_COUNT,
        CALL_COUNT)
    VALUES (P_BUCKET, P_USER, P_PROJ, P_RES,
         P_RTYPE, P_UTYPE, P_USUBTYPE, P_DELTA,  P_CALL)
    ON CONFLICT (BUCKET_UTC, USER_ID, PROJECT_ID, RESOURCE_ID, RESOURCE_TYPE, UNIT_TYPE, UNIT_SUBTYPE)
    DO UPDATE
        SET UNIT_COUNT = USAGE_MINUTE_ROLLUP.UNIT_COUNT + EXCLUDED.UNIT_COUNT,
            CALL_COUNT = USAGE_MINUTE_ROLLUP.CALL_COUNT + EXCLUDED.CALL_COUNT;
END$$;



CREATE OR REPLACE FUNCTION USAGE_ROLLUP_TRG()
RETURNS TRIGGER LANGUAGE PLPGSQL AS $$
DECLARE
    V_OLD INTEGER := 0;
    V_NEW BIGINT := 0;
    V_DELTA INTEGER := 0;
    V_BUCKET TIMESTAMPTZ;
    V_USER VARCHAR(36);
BEGIN
    IF TG_OP = 'INSERT' THEN
        V_NEW := COALESCE(NEW.UNIT_COUNT, 0);
        V_DELTA := V_NEW;
        V_BUCKET := DATE_TRUNC('MINUTE', NEW.TRANSACTION_TIME AT TIME ZONE 'UTC');
        SELECT UP.USER_ID INTO V_USER FROM USER_PROJECT UP WHERE UP.PROJECT_ID = NEW.PROJECT_ID;

        --
        PERFORM _USAGE_ROLLUP_APPLY(
            V_BUCKET, V_USER, NEW.PROJECT_ID, NEW.RESOURCE_ID,
            NEW.RESOURCE_TYPE, NEW.UNIT_TYPE, NEW.UNIT_SUBTYPE, V_DELTA, 1);
        RETURN NEW;

    ELSIF TG_OP = 'UPDATE' THEN
        V_OLD := COALESCE(OLD.UNIT_COUNT, 0);
        V_NEW := COALESCE(NEW.UNIT_COUNT, 0);

        IF DATE_TRUNC('MINUTE', OLD.TRANSACTION_TIME AT TIME ZONE 'UTC')
             <> DATE_TRUNC('MINUTE', NEW.TRANSACTION_TIME AT TIME ZONE 'UTC')
           OR OLD.PROJECT_ID     <> NEW.PROJECT_ID
           OR OLD.RESOURCE_ID    <> NEW.RESOURCE_ID
           OR OLD.RESOURCE_TYPE  <> NEW.RESOURCE_TYPE
           OR OLD.UNIT_TYPE      <> NEW.UNIT_TYPE
           OR OLD.UNIT_SUBTYPE   <> NEW.UNIT_SUBTYPE THEN

            V_BUCKET := DATE_TRUNC('MINUTE', OLD.TRANSACTION_TIME AT TIME ZONE 'UTC');
            SELECT UP.USER_ID INTO V_USER FROM USER_PROJECT UP WHERE UP.PROJECT_ID = OLD.PROJECT_ID;
            PERFORM _USAGE_ROLLUP_APPLY(
                V_BUCKET, V_USER, OLD.PROJECT_ID, OLD.RESOURCE_ID,
                OLD.RESOURCE_TYPE, OLD.UNIT_TYPE, OLD.UNIT_SUBTYPE, -V_OLD, 0);

            V_BUCKET := DATE_TRUNC('MINUTE', NEW.TRANSACTION_TIME AT TIME ZONE 'UTC');
            SELECT UP.USER_ID INTO V_USER FROM USER_PROJECT UP WHERE UP.PROJECT_ID = NEW.PROJECT_ID;
            PERFORM _USAGE_ROLLUP_APPLY(
                V_BUCKET, V_USER, NEW.PROJECT_ID, NEW.RESOURCE_ID,
                NEW.RESOURCE_TYPE, NEW.UNIT_TYPE, NEW.UNIT_SUBTYPE, V_NEW, 0);
        ELSE
            V_DELTA := V_NEW - V_OLD;
            V_BUCKET := DATE_TRUNC('MINUTE', NEW.TRANSACTION_TIME AT TIME ZONE 'UTC');
            SELECT UP.USER_ID INTO V_USER FROM USER_PROJECT UP WHERE UP.PROJECT_ID = NEW.PROJECT_ID;
            PERFORM _USAGE_ROLLUP_APPLY(
                V_BUCKET, V_USER, NEW.PROJECT_ID, NEW.RESOURCE_ID,
                NEW.RESOURCE_TYPE, NEW.UNIT_TYPE, NEW.UNIT_SUBTYPE, V_DELTA, 0);
        END IF;
        RETURN NEW;

    ELSIF TG_OP = 'DELETE' THEN
        V_OLD := COALESCE(OLD.UNIT_COUNT, 0);
        V_BUCKET := DATE_TRUNC('MINUTE', OLD.TRANSACTION_TIME AT TIME ZONE 'UTC');
        SELECT UP.USER_ID INTO V_USER FROM USER_PROJECT UP WHERE UP.PROJECT_ID = OLD.PROJECT_ID;
        PERFORM _USAGE_ROLLUP_APPLY(
            V_BUCKET, V_USER, OLD.PROJECT_ID, OLD.RESOURCE_ID,
            OLD.RESOURCE_TYPE, OLD.UNIT_TYPE, OLD.UNIT_SUBTYPE, -V_OLD, -1);
        RETURN OLD;
    END IF;
END$$;

CREATE TRIGGER TRG_USAGE_ROLLUP_INS
AFTER INSERT ON USAGE
FOR EACH ROW EXECUTE FUNCTION USAGE_ROLLUP_TRG();

CREATE TRIGGER TRG_USAGE_ROLLUP_UPD
AFTER UPDATE ON USAGE
FOR EACH ROW EXECUTE FUNCTION USAGE_ROLLUP_TRG();

CREATE TRIGGER TRG_USAGE_ROLLUP_DEL
AFTER DELETE ON USAGE
FOR EACH ROW EXECUTE FUNCTION USAGE_ROLLUP_TRG();

-- OPTIONAL: SPEED UP SCANS DURING BACKFILL
CREATE INDEX IF NOT EXISTS USAGE_PROJ_TIME_IDX
  ON USAGE (PROJECT_ID, TRANSACTION_TIME);

CREATE INDEX IF NOT EXISTS USAGE_MINUTE_ROLLUP_USER_IDX
  ON USAGE_MINUTE_ROLLUP (USER_ID);

CREATE INDEX IF NOT EXISTS USAGE_MINUTE_ROLLUP_PROJ_IDX
  ON USAGE_MINUTE_ROLLUP (PROJECT_ID);

CREATE INDEX IF NOT EXISTS USAGE_MINUTE_ROLLUP_USER_IDX
  ON USAGE_MINUTE_ROLLUP (USER_ID);

BEGIN;

-- TRUNCATE USAGE_MINUTE_ROLLUP;

WITH SRC AS (
  SELECT
    DATE_TRUNC('MINUTE', U.TRANSACTION_TIME AT TIME ZONE 'UTC') AS BUCKET_UTC,
    UP.USER_ID,
    U.PROJECT_ID,
    U.RESOURCE_ID,
    U.RESOURCE_TYPE,
    U.UNIT_TYPE,
    U.UNIT_SUBTYPE,
    SUM(U.UNIT_COUNT)::INT AS UNIT_COUNT,
    COUNT(UP.USER_ID) AS CALL_COUNT
  FROM USAGE U
  -- IF USER_PROJECT CAN HAVE DUPLICATE ROWS, DISTINCT IT:
  JOIN (SELECT DISTINCT PROJECT_ID, USER_ID FROM USER_PROJECT) UP
    ON UP.PROJECT_ID = U.PROJECT_ID
  /* OPTIONAL TIME WINDOW
  WHERE U.TRANSACTION_TIME >= :FROM_TS
    AND U.TRANSACTION_TIME <  :TO_TS
  */
  GROUP BY 1,2,3,4,5,6,7
--   HAVING COUNT(UP.USER_ID) > 1
)
INSERT INTO USAGE_MINUTE_ROLLUP (
  BUCKET_UTC, USER_ID, PROJECT_ID, RESOURCE_ID, RESOURCE_TYPE, UNIT_TYPE, UNIT_SUBTYPE, UNIT_COUNT, CALL_COUNT
)
SELECT * FROM SRC
ON CONFLICT (BUCKET_UTC, USER_ID, PROJECT_ID, RESOURCE_ID, RESOURCE_TYPE, UNIT_TYPE, UNIT_SUBTYPE)
DO UPDATE SET UNIT_COUNT = EXCLUDED.UNIT_COUNT, CALL_COUNT = EXCLUDED.CALL_COUNT;

COMMIT;

DROP VIEW IF EXISTS USAGE_MINUTE_ROLLUP_WITH_PRICE CASCADE;
CREATE OR REPLACE VIEW USAGE_MINUTE_ROLLUP_WITH_PRICE AS
  SELECT
    BUCKET_UTC,
    EXTRACT(YEAR   FROM (U.BUCKET_UTC AT TIME ZONE 'UTC'))    AS YEAR,
    EXTRACT(MONTH  FROM (U.BUCKET_UTC AT TIME ZONE 'UTC'))    AS MONTH,
    EXTRACT(DAY    FROM (U.BUCKET_UTC AT TIME ZONE 'UTC'))    AS DAY,
    EXTRACT(HOUR   FROM (U.BUCKET_UTC AT TIME ZONE 'UTC'))    AS HOUR,
    EXTRACT(MINUTE FROM (U.BUCKET_UTC AT TIME ZONE 'UTC'))    AS MINUTE,
    U.USER_ID,
    U.PROJECT_ID,
    U.RESOURCE_ID,
    U.RESOURCE_TYPE,
    U.UNIT_TYPE,
    MAX(INPUT_PRICE_PER_1K_TOKENS) AS INPUT_PRICE_PER_1K_TOKENS,
    MAX(OUTPUT_PRICE_PER_1K_TOKENS) AS OUTPUT_PRICE_PER_1K_TOKENS,

    -- INPUT
    SUM(CALL_COUNT) FILTER (WHERE UNIT_TYPE = 'TOKEN' AND U.UNIT_SUBTYPE = 'INPUT') AS INPUT_COUNT,
    SUM(UNIT_COUNT) FILTER (WHERE UNIT_TYPE = 'TOKEN' AND U.UNIT_SUBTYPE = 'INPUT') AS INPUT_TOKENS,
    SUM(P.INPUT_PRICE_PER_1K_TOKENS * U.UNIT_COUNT / 1000) FILTER (WHERE UNIT_TYPE = 'TOKEN' AND U.UNIT_SUBTYPE = 'INPUT') AS INPUT_COST,

    -- OUTPUT
    SUM(CALL_COUNT) FILTER (WHERE UNIT_TYPE = 'TOKEN' AND U.UNIT_SUBTYPE = 'OUTPUT') AS OUTPUT_COUNT,
    SUM(UNIT_COUNT) FILTER (WHERE UNIT_TYPE = 'TOKEN' AND U.UNIT_SUBTYPE = 'OUTPUT') AS OUTPUT_TOKENS,
    SUM(P.OUTPUT_PRICE_PER_1K_TOKENS * U.UNIT_COUNT / 1000) FILTER (WHERE  UNIT_TYPE = 'TOKEN' AND U.UNIT_SUBTYPE = 'OUTPUT') AS OUTPUT_COST
  FROM USAGE_MINUTE_ROLLUP U
  LEFT JOIN PROCESSOR_PROVIDER_PRICING P
    ON U.RESOURCE_TYPE = P.PROCESSOR_PROVIDER_ID
GROUP BY
    BUCKET_UTC,
    YEAR, MONTH, DAY, HOUR, MINUTE,
    U.USER_ID,
    U.PROJECT_ID,
    U.RESOURCE_ID,
    U.RESOURCE_TYPE,
    U.UNIT_TYPE;

DROP VIEW IF EXISTS USAGE_MINUTELY_V;
CREATE OR REPLACE VIEW USAGE_MINUTELY_V (
    USER_ID, PROJECT_ID, YEAR, MONTH, DAY, HOUR, MINUTE,
    RESOURCE_TYPE, RESOURCE_ID,
    INPUT_COST, INPUT_PRICE, INPUT_TOKENS, INPUT_COUNT,
    OUTPUT_COST, OUTPUT_PRICE, OUTPUT_TOKENS, OUTPUT_COUNT,
    TOTAL_COST, TOTAL_TOKENS) AS
SELECT
    USER_ID,
    PROJECT_ID,
    YEAR,
    MONTH,
    DAY,
    HOUR,
    MINUTE,
    RESOURCE_TYPE,
    RESOURCE_ID,
    SUM(INPUT_COST) AS INPUT_COST,
    MAX(INPUT_PRICE_PER_1K_TOKENS) AS INPUT_PRICE,
    SUM(INPUT_TOKENS) AS INPUT_TOKENS,
    SUM(INPUT_COUNT) AS INPUT_COUNT,
    SUM(OUTPUT_COST) AS OUTPUT_PRICE,
    MAX(OUTPUT_PRICE_PER_1K_TOKENS) AS OUTPUT_PRICE,
    SUM(OUTPUT_TOKENS) AS OUTPUT_TOKENS,
    SUM(OUTPUT_COUNT) AS OUTPUT_COUNT,
    SUM(INPUT_COST + OUTPUT_COST) AS TOTAL_COST,
    SUM(INPUT_TOKENS + OUTPUT_TOKENS) AS TOTAL_TOKENS
FROM USAGE_MINUTE_ROLLUP_WITH_PRICE
GROUP BY USER_ID, PROJECT_ID, YEAR, MONTH, DAY, HOUR, MINUTE, RESOURCE_TYPE, RESOURCE_ID
ORDER BY YEAR DESC, MONTH DESC, DAY DESC, HOUR DESC, MINUTE DESC, RESOURCE_TYPE;


DROP VIEW IF EXISTS USAGE_HOURLY_V;
CREATE OR REPLACE VIEW USAGE_HOURLY_V (
    USER_ID, PROJECT_ID, YEAR, MONTH, DAY, HOUR,
    RESOURCE_TYPE, RESOURCE_ID,
    INPUT_COST, INPUT_PRICE, INPUT_TOKENS, INPUT_COUNT,
    OUTPUT_COST, OUTPUT_PRICE, OUTPUT_TOKENS, OUTPUT_COUNT,
    TOTAL_COST, TOTAL_TOKENS) AS
SELECT
    USER_ID,
    PROJECT_ID,
    YEAR,
    MONTH,
    DAY,
    HOUR,
    RESOURCE_TYPE,
    RESOURCE_ID,
    SUM(INPUT_COST) AS INPUT_COST,
    MAX(INPUT_PRICE_PER_1K_TOKENS) AS INPUT_PRICE,
    SUM(INPUT_TOKENS) AS INPUT_TOKENS,
    SUM(INPUT_COUNT) AS INPUT_COUNT,
    SUM(OUTPUT_COST) AS OUTPUT_PRICE,
    MAX(OUTPUT_PRICE_PER_1K_TOKENS) AS OUTPUT_PRICE,
    SUM(OUTPUT_TOKENS) AS OUTPUT_TOKENS,
    SUM(OUTPUT_COUNT) AS OUTPUT_COUNT,
    SUM(INPUT_COST + OUTPUT_COST) AS TOTAL_COST,
    SUM(INPUT_TOKENS + OUTPUT_TOKENS) AS TOTAL_TOKENS
FROM USAGE_MINUTE_ROLLUP_WITH_PRICE
GROUP BY USER_ID, PROJECT_ID, YEAR, MONTH, DAY, HOUR, RESOURCE_TYPE, RESOURCE_ID
ORDER BY YEAR DESC, MONTH DESC, DAY DESC, HOUR DESC, RESOURCE_TYPE;

-- DAILY REPORT
DROP VIEW IF EXISTS USAGE_DAILY_V;
CREATE OR REPLACE VIEW USAGE_DAILY_V (
    USER_ID, PROJECT_ID, YEAR, MONTH, DAY,
    RESOURCE_TYPE, RESOURCE_ID,
    INPUT_COST, INPUT_PRICE, INPUT_TOKENS, INPUT_COUNT,
    OUTPUT_COST, OUTPUT_PRICE, OUTPUT_TOKENS, OUTPUT_COUNT,
    TOTAL_COST, TOTAL_TOKENS) AS
SELECT
    USER_ID,
    PROJECT_ID,
    YEAR,
    MONTH,
    DAY,
    RESOURCE_TYPE,
    RESOURCE_ID,
    SUM(INPUT_COST) AS INPUT_COST,
    MAX(INPUT_PRICE_PER_1K_TOKENS) AS INPUT_PRICE,
    SUM(INPUT_TOKENS) AS INPUT_TOKENS,
    SUM(INPUT_COUNT) AS INPUT_COUNT,
    SUM(OUTPUT_COST) AS OUTPUT_PRICE,
    MAX(OUTPUT_PRICE_PER_1K_TOKENS) AS OUTPUT_PRICE,
    SUM(OUTPUT_TOKENS) AS OUTPUT_TOKENS,
    SUM(OUTPUT_COUNT) AS OUTPUT_COUNT,
    SUM(INPUT_COST + OUTPUT_COST) AS TOTAL_COST,
    SUM(INPUT_TOKENS + OUTPUT_TOKENS) AS TOTAL_TOKENS
FROM USAGE_MINUTE_ROLLUP_WITH_PRICE
GROUP BY USER_ID, PROJECT_ID, YEAR, MONTH, DAY, RESOURCE_TYPE, RESOURCE_ID
ORDER BY YEAR DESC, MONTH DESC, DAY DESC, RESOURCE_TYPE, RESOURCE_ID;

-- MONTHLY REPORT
DROP VIEW IF EXISTS USAGE_MONTHLY_V;
CREATE OR REPLACE VIEW USAGE_MONTHLY_V (
    USER_ID, PROJECT_ID, YEAR, DAY,
    RESOURCE_TYPE, RESOURCE_ID,
    INPUT_COST, INPUT_PRICE, INPUT_TOKENS, INPUT_COUNT,
    OUTPUT_COST, OUTPUT_PRICE, OUTPUT_TOKENS, OUTPUT_COUNT,
    TOTAL_COST, TOTAL_TOKENS) AS
SELECT
    USER_ID,
    PROJECT_ID,
    YEAR,
    MONTH,
    RESOURCE_TYPE,
    RESOURCE_ID,
    SUM(INPUT_COST) AS INPUT_COST,
    MAX(INPUT_PRICE_PER_1K_TOKENS) AS INPUT_PRICE,
    SUM(INPUT_TOKENS) AS INPUT_TOKENS,
    SUM(INPUT_COUNT) AS INPUT_COUNT,
    SUM(OUTPUT_COST) AS OUTPUT_PRICE,
    MAX(OUTPUT_PRICE_PER_1K_TOKENS) AS OUTPUT_PRICE,
    SUM(OUTPUT_TOKENS) AS OUTPUT_TOKENS,
    SUM(OUTPUT_COUNT) AS OUTPUT_COUNT,
    SUM(INPUT_COST + OUTPUT_COST) AS TOTAL_COST,
    SUM(INPUT_TOKENS + OUTPUT_TOKENS) AS TOTAL_TOKENS
FROM USAGE_MINUTE_ROLLUP_WITH_PRICE
GROUP BY USER_ID, PROJECT_ID, YEAR, MONTH, RESOURCE_TYPE, RESOURCE_ID
ORDER BY YEAR DESC, MONTH DESC, RESOURCE_TYPE, RESOURCE_ID;

--- YEARLY REPORT
DROP VIEW IF EXISTS USAGE_YEARLY_V;
CREATE OR REPLACE VIEW USAGE_YEARLY_V (
    USER_ID, PROJECT_ID, YEAR,
    RESOURCE_TYPE, RESOURCE_ID,
    INPUT_COST, INPUT_PRICE, INPUT_TOKENS, INPUT_COUNT,
    OUTPUT_COST, OUTPUT_PRICE, OUTPUT_TOKENS, OUTPUT_COUNT,
    TOTAL_COST, TOTAL_TOKENS) AS
SELECT
    USER_ID,
    PROJECT_ID,
    YEAR,
    RESOURCE_TYPE,
    RESOURCE_ID,
    SUM(INPUT_COST) AS INPUT_COST,
    MAX(INPUT_PRICE_PER_1K_TOKENS) AS INPUT_PRICE,
    SUM(INPUT_TOKENS) AS INPUT_TOKENS,
    SUM(INPUT_COUNT) AS INPUT_COUNT,
    SUM(OUTPUT_COST) AS OUTPUT_PRICE,
    MAX(OUTPUT_PRICE_PER_1K_TOKENS) AS OUTPUT_PRICE,
    SUM(OUTPUT_TOKENS) AS OUTPUT_TOKENS,
    SUM(OUTPUT_COUNT) AS OUTPUT_COUNT,
    SUM(INPUT_COST + OUTPUT_COST) AS TOTAL_COST,
    SUM(INPUT_TOKENS + OUTPUT_TOKENS) AS TOTAL_TOKENS
FROM USAGE_MINUTE_ROLLUP_WITH_PRICE
GROUP BY USER_ID, PROJECT_ID, YEAR, RESOURCE_TYPE, RESOURCE_ID
ORDER BY YEAR DESC, RESOURCE_TYPE, RESOURCE_ID;


--- YEARLY REPORT
DROP VIEW IF EXISTS USAGE_ALL_V;
CREATE OR REPLACE VIEW USAGE_V (
    USER_ID, PROJECT_ID, YEAR,
    RESOURCE_TYPE, RESOURCE_ID,
    INPUT_COST, INPUT_PRICE, INPUT_TOKENS, INPUT_COUNT,
    OUTPUT_COST, OUTPUT_PRICE, OUTPUT_TOKENS, OUTPUT_COUNT,
    TOTAL_COST, TOTAL_TOKENS) AS
SELECT
    USER_ID,
    PROJECT_ID,
    YEAR,
    RESOURCE_TYPE,
    RESOURCE_ID,
    SUM(INPUT_COST) AS INPUT_COST,
    MAX(INPUT_PRICE_PER_1K_TOKENS) AS INPUT_PRICE,
    SUM(INPUT_TOKENS) AS INPUT_TOKENS,
    SUM(INPUT_COUNT) AS INPUT_COUNT,
    SUM(OUTPUT_COST) AS OUTPUT_PRICE,
    MAX(OUTPUT_PRICE_PER_1K_TOKENS) AS OUTPUT_PRICE,
    SUM(OUTPUT_TOKENS) AS OUTPUT_TOKENS,
    SUM(OUTPUT_COUNT) AS OUTPUT_COUNT,
    SUM(INPUT_COST + OUTPUT_COST) AS TOTAL_COST,
    SUM(INPUT_TOKENS + OUTPUT_TOKENS) AS TOTAL_TOKENS
FROM USAGE_MINUTE_ROLLUP_WITH_PRICE
GROUP BY USER_ID, PROJECT_ID, YEAR, RESOURCE_TYPE, RESOURCE_ID
ORDER BY YEAR DESC, RESOURCE_TYPE, RESOURCE_ID;

-----------------------------------
------ USAGE TIERING VIEWS
-----------------------------------
DROP VIEW USER_PROJECT_CURRENT_USAGE_SNAPSHOT CASCADE;
CREATE OR REPLACE VIEW USER_PROJECT_CURRENT_USAGE_SNAPSHOT AS
SELECT
    USER_ID,
    PROJECT_ID,
    RESOURCE_TYPE,

    -- INPUT TOKEN USAGE
    COALESCE(SUM(INPUT_TOKENS) FILTER (WHERE DATE_TRUNC('MINUTE', BUCKET_UTC) = DATE_TRUNC('MINUTE', CURRENT_TIMESTAMP)), 0) AS CUR_MINUTE_INPUT_TOKENS,
    COALESCE(SUM(INPUT_TOKENS) FILTER (WHERE DATE_TRUNC('HOUR',   BUCKET_UTC) = DATE_TRUNC('HOUR',   CURRENT_TIMESTAMP)), 0) AS CUR_HOUR_INPUT_TOKENS,
    COALESCE(SUM(INPUT_TOKENS) FILTER (WHERE DATE_TRUNC('DAY',    BUCKET_UTC) = DATE_TRUNC('DAY',    CURRENT_TIMESTAMP)), 0) AS CUR_DAY_INPUT_TOKENS,
    COALESCE(SUM(INPUT_TOKENS) FILTER (WHERE DATE_TRUNC('WEEK',   BUCKET_UTC) = DATE_TRUNC('WEEK',   CURRENT_TIMESTAMP)), 0) AS CUR_WEEK_INPUT_TOKENS,
    COALESCE(SUM(INPUT_TOKENS) FILTER (WHERE DATE_TRUNC('MONTH',  BUCKET_UTC) = DATE_TRUNC('MONTH',  CURRENT_TIMESTAMP)), 0) AS CUR_MONTH_INPUT_TOKENS,
    COALESCE(SUM(INPUT_TOKENS) FILTER (WHERE DATE_TRUNC('YEAR',   BUCKET_UTC) = DATE_TRUNC('YEAR',   CURRENT_TIMESTAMP)), 0) AS CUR_YEAR_INPUT_TOKENS,

    -- OUTPUT TOKEN USAGE
    COALESCE(SUM(OUTPUT_TOKENS) FILTER (WHERE DATE_TRUNC('MINUTE', BUCKET_UTC) = DATE_TRUNC('MINUTE', CURRENT_TIMESTAMP)), 0) AS CUR_MINUTE_OUTPUT_TOKENS,
    COALESCE(SUM(OUTPUT_TOKENS) FILTER (WHERE DATE_TRUNC('HOUR',   BUCKET_UTC) = DATE_TRUNC('HOUR',   CURRENT_TIMESTAMP)), 0) AS CUR_HOUR_OUTPUT_TOKENS,
    COALESCE(SUM(OUTPUT_TOKENS) FILTER (WHERE DATE_TRUNC('DAY',    BUCKET_UTC) = DATE_TRUNC('DAY',    CURRENT_TIMESTAMP)), 0) AS CUR_DAY_OUTPUT_TOKENS,
    COALESCE(SUM(OUTPUT_TOKENS) FILTER (WHERE DATE_TRUNC('WEEK',   BUCKET_UTC) = DATE_TRUNC('WEEK',   CURRENT_TIMESTAMP)), 0) AS CUR_WEEK_OUTPUT_TOKENS,
    COALESCE(SUM(OUTPUT_TOKENS) FILTER (WHERE DATE_TRUNC('MONTH',  BUCKET_UTC) = DATE_TRUNC('MONTH',  CURRENT_TIMESTAMP)), 0) AS CUR_MONTH_OUTPUT_TOKENS,
    COALESCE(SUM(OUTPUT_TOKENS) FILTER (WHERE DATE_TRUNC('YEAR',   BUCKET_UTC) = DATE_TRUNC('YEAR',   CURRENT_TIMESTAMP)), 0) AS CUR_YEAR_OUTPUT_TOKENS,

    -- INPUT COST USAGE
    COALESCE(SUM(INPUT_COST) FILTER (WHERE DATE_TRUNC('MINUTE', BUCKET_UTC) = DATE_TRUNC('MINUTE', CURRENT_TIMESTAMP)), 0.0) AS CUR_MINUTE_INPUT_COST,
    COALESCE(SUM(INPUT_COST) FILTER (WHERE DATE_TRUNC('HOUR',   BUCKET_UTC) = DATE_TRUNC('HOUR',   CURRENT_TIMESTAMP)), 0.0) AS CUR_HOUR_INPUT_COST,
    COALESCE(SUM(INPUT_COST) FILTER (WHERE DATE_TRUNC('DAY',    BUCKET_UTC) = DATE_TRUNC('DAY',    CURRENT_TIMESTAMP)), 0.0) AS CUR_DAY_INPUT_COST,
    COALESCE(SUM(INPUT_COST) FILTER (WHERE DATE_TRUNC('WEEK',   BUCKET_UTC) = DATE_TRUNC('WEEK',   CURRENT_TIMESTAMP)), 0.0) AS CUR_WEEK_INPUT_COST,
    COALESCE(SUM(INPUT_COST) FILTER (WHERE DATE_TRUNC('MONTH',  BUCKET_UTC) = DATE_TRUNC('MONTH',  CURRENT_TIMESTAMP)), 0.0) AS CUR_MONTH_INPUT_COST,
    COALESCE(SUM(INPUT_COST) FILTER (WHERE DATE_TRUNC('YEAR',   BUCKET_UTC) = DATE_TRUNC('YEAR',   CURRENT_TIMESTAMP)), 0.0) AS CUR_YEAR_INPUT_COST,

    -- OUTPUT COST USAGE
    COALESCE(SUM(OUTPUT_COST) FILTER (WHERE DATE_TRUNC('MINUTE', BUCKET_UTC) = DATE_TRUNC('MINUTE', CURRENT_TIMESTAMP)), 0.0) AS CUR_MINUTE_OUTPUT_COST,
    COALESCE(SUM(OUTPUT_COST) FILTER (WHERE DATE_TRUNC('HOUR',   BUCKET_UTC) = DATE_TRUNC('HOUR',   CURRENT_TIMESTAMP)), 0.0) AS CUR_HOUR_OUTPUT_COST,
    COALESCE(SUM(OUTPUT_COST) FILTER (WHERE DATE_TRUNC('DAY',    BUCKET_UTC) = DATE_TRUNC('DAY',    CURRENT_TIMESTAMP)), 0.0) AS CUR_DAY_OUTPUT_COST,
    COALESCE(SUM(OUTPUT_COST) FILTER (WHERE DATE_TRUNC('WEEK',   BUCKET_UTC) = DATE_TRUNC('WEEK',   CURRENT_TIMESTAMP)), 0.0) AS CUR_WEEK_OUTPUT_COST,
    COALESCE(SUM(OUTPUT_COST) FILTER (WHERE DATE_TRUNC('MONTH',  BUCKET_UTC) = DATE_TRUNC('MONTH',  CURRENT_TIMESTAMP)), 0.0) AS CUR_MONTH_OUTPUT_COST,
    COALESCE(SUM(OUTPUT_COST) FILTER (WHERE DATE_TRUNC('YEAR',   BUCKET_UTC) = DATE_TRUNC('YEAR',   CURRENT_TIMESTAMP)), 0.0) AS CUR_YEAR_OUTPUT_COST
--- ROLLUP TABLE
FROM USAGE_MINUTE_ROLLUP_WITH_PRICE
WHERE EXTRACT(YEAR FROM BUCKET_UTC) = EXTRACT(YEAR FROM CURRENT_TIMESTAMP)
GROUP BY USER_ID, PROJECT_ID, RESOURCE_TYPE;

----
DROP VIEW IF EXISTS USER_PROJECT_CURRENT_USAGE_WITH_TIER CASCADE;
CREATE OR REPLACE VIEW USER_PROJECT_CURRENT_USAGE_WITH_TIER AS
SELECT
    P.USER_ID,
    U.PROJECT_ID,
    P.TIER_ID,
    T.PER_MINUTE,
    T.PER_HOUR,
    T.PER_DAY,
    T.PER_MONTH,
    T.PER_YEAR,
    T.COST_PER_MINUTE,
    T.COST_PER_HOUR,
    T.COST_PER_DAY,
    T.COST_PER_MONTH,
    T.COST_PER_YEAR,

    -- TOTAL TOKENS (INPUT + OUTPUT)
    COALESCE(SUM(CUR_MINUTE_INPUT_TOKENS + CUR_MINUTE_OUTPUT_TOKENS), 0) AS CUR_MINUTE_TOTAL_TOKENS,
    COALESCE(SUM(CUR_HOUR_INPUT_TOKENS   + CUR_HOUR_OUTPUT_TOKENS),   0) AS CUR_HOUR_TOTAL_TOKENS,
    COALESCE(SUM(CUR_DAY_INPUT_TOKENS    + CUR_DAY_OUTPUT_TOKENS),    0) AS CUR_DAY_TOTAL_TOKENS,
    COALESCE(SUM(CUR_WEEK_INPUT_TOKENS   + CUR_WEEK_OUTPUT_TOKENS),   0) AS CUR_WEEK_TOTAL_TOKENS,
    COALESCE(SUM(CUR_MONTH_INPUT_TOKENS  + CUR_MONTH_OUTPUT_TOKENS),  0) AS CUR_MONTH_TOTAL_TOKENS,
    COALESCE(SUM(CUR_YEAR_INPUT_TOKENS   + CUR_YEAR_OUTPUT_TOKENS),   0) AS CUR_YEAR_TOTAL_TOKENS,

    -- TOTAL COSTS (INPUT + OUTPUT)
    COALESCE(SUM(CUR_MINUTE_INPUT_COST + CUR_MINUTE_OUTPUT_COST), 0.0) AS CUR_MINUTE_TOTAL_COST,
    COALESCE(SUM(CUR_HOUR_INPUT_COST   + CUR_HOUR_OUTPUT_COST),   0.0) AS CUR_HOUR_TOTAL_COST,
    COALESCE(SUM(CUR_DAY_INPUT_COST    + CUR_DAY_OUTPUT_COST),    0.0) AS CUR_DAY_TOTAL_COST,
    COALESCE(SUM(CUR_WEEK_INPUT_COST   + CUR_WEEK_OUTPUT_COST),   0.0) AS CUR_WEEK_TOTAL_COST,
    COALESCE(SUM(CUR_MONTH_INPUT_COST  + CUR_MONTH_OUTPUT_COST),  0.0) AS CUR_MONTH_TOTAL_COST,
    COALESCE(SUM(CUR_YEAR_INPUT_COST   + CUR_YEAR_OUTPUT_COST),   0.0) AS CUR_YEAR_TOTAL_COST
FROM USER_PROJECT_CURRENT_USAGE_SNAPSHOT U
JOIN USER_PROFILE P ON P.USER_ID = U.USER_ID
JOIN USAGE_TIER T ON T.ID = P.TIER_ID
GROUP BY
    P.USER_ID,
    U.PROJECT_ID,
    P.TIER_ID,
    T.PER_MINUTE, T.PER_HOUR, T.PER_DAY, T.PER_MONTH, T.PER_YEAR,
    T.COST_PER_MINUTE, T.COST_PER_HOUR, T.COST_PER_DAY, T.COST_PER_MONTH, T.COST_PER_YEAR;
GRANT SELECT ON USER_PROJECT_CURRENT_USAGE_WITH_TIER TO ISM_DB_USER;

----
DROP VIEW IF EXISTS USER_PROJECT_CURRENT_USAGE_REPORT;
CREATE OR REPLACE VIEW USER_PROJECT_CURRENT_USAGE_REPORT AS
SELECT
    USER_ID,
    PROJECT_ID,
    ROUND(100 * CUR_MINUTE_TOTAL_TOKENS / NULLIF(PER_MINUTE, 0), 2) AS PCT_MINUTE_TOKENS_USED,
    ROUND(100 * CUR_HOUR_TOTAL_TOKENS / NULLIF(PER_HOUR, 0), 2) AS PCT_HOUR_TOKENS_USED,
    ROUND(100 * CUR_DAY_TOTAL_TOKENS / NULLIF(PER_DAY, 0), 2) AS PCT_DAY_TOKENS_USED,
    ROUND(100 * CUR_MONTH_TOTAL_TOKENS / NULLIF(PER_MONTH, 0), 2) AS PCT_MONTH_TOKENS_USED,
    ROUND(100 * CUR_YEAR_TOTAL_TOKENS / NULLIF(PER_YEAR, 0), 2) AS PCT_YEAR_TOKENS_USED,
    ROUND(100 * CUR_MINUTE_TOTAL_COST / NULLIF(COST_PER_MINUTE, 0), 2) AS PCT_MINUTE_COST_USED,
    ROUND(100 * CUR_HOUR_TOTAL_COST / NULLIF(COST_PER_HOUR, 0), 2) AS PCT_HOUR_COST_USED,
    ROUND(100 * CUR_DAY_TOTAL_COST / NULLIF(COST_PER_DAY, 0), 2) AS PCT_DAY_COST_USED,
    ROUND(100 * CUR_MONTH_TOTAL_COST / NULLIF(COST_PER_MONTH, 0), 2) AS PCT_MONTH_COST_USED,
    ROUND(100 * CUR_YEAR_TOTAL_COST / NULLIF(COST_PER_YEAR, 0), 2) AS PCT_YEAR_COST_USED
FROM USER_PROJECT_CURRENT_USAGE_WITH_TIER;


GRANT SELECT ON USAGE_MINUTE_ROLLUP_WITH_PRICE TO ISM_DB_USER;
GRANT SELECT ON USAGE_MINUTELY_V TO ISM_DB_USER;
GRANT SELECT ON USAGE_HOURLY_V TO ISM_DB_USER;
GRANT SELECT ON USAGE_DAILY_V TO ISM_DB_USER;
GRANT SELECT ON USAGE_MONTHLY_V TO ISM_DB_USER;
GRANT SELECT ON USAGE_YEARLY_V TO ISM_DB_USER;
GRANT SELECT ON USER_PROJECT_CURRENT_USAGE_SNAPSHOT TO ISM_DB_USER;
GRANT SELECT ON USER_PROJECT_CURRENT_USAGE_REPORT TO ISM_DB_USER;
GRANT SELECT ON USER_PROJECT_CURRENT_USAGE_WITH_TIER TO ISM_DB_USER;
