name: alethic-ism-db
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - python-dotenv
  - pyyaml
  - pydantic
  - psycopg2
  - transformers
  - nltk
  - torch
  - name: alethic-ism-core 
    url: file:///app/conda/env/local_channel
    type: tar.bz2
