name: alethic-ism-db
channels:
#  - file:///app/conda/env/local_channel
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - python-dotenv
  - pyyaml
  - pydantic
  - psycopg2
  - transformers
  - nltk
  - pytorch
#  - alethic-ism-core 
