name: alethic-ism-db
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - python-dotenv
  - pyyaml
  - pydantic
  - psycopg2
  - transformers
  - nltk
  - redis-py
  - pytorch
  - restrictedpython
  - alethic-ism-core
