name: alethic-ism-db
channels:
  - file:///app/conda/env/local_channel
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - python-dotenv
  - pyyaml
  - pydantic
#  - psycopg2
#  - transformers
#  - nltk
  - redis-py
#  - pytorch
  - pytest
#  - nats-py
#  - restrictedpython
  - alethic-ism-core 
