name: Docker Build and Push Python to PyPi (alethic-ism-db python module)

on:
  push:
    tags:
      - 'v*'

#on:
#  push:
#    branches:
#      - main

jobs:   
  build-and-upload:
    permissions:
      contents: write
      
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      id: code_checkout
      uses: actions/checkout@v4

    - name: Assign Environment Variables for Build & Deployment Process
      id: setup_variables
      run: |
        COMMIT_ID=$(echo $GITHUB_SHA | head -c7)
        NAMESPACE="krasaee"
        PROJECT_NAME="alethic-ism-db"
        IMAGE="$NAMESPACE/$PROJECT_NAME:$COMMIT_ID"
        
        echo "COMMIT_ID=$COMMIT_ID" >> "$GITHUB_ENV"
        echo "IMAGE=$IMAGE" >> "$GITHUB_ENV"

    - name: Create PyPI config file for twine upload
      run: |
        mkdir -p /tmp/secrets
        echo '[pypi]' > /tmp/secrets/pypirc
        echo 'username = __token__' >> /tmp/secrets/pypirc
        echo 'password = ${{ secrets.PYPI_API_KEY }}' >> /tmp/secrets/pypirc
        cat /tmp/secrets/pypirc

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Package and Upload to PyPi
      run: |
        echo "Building image $IMAGE"
        sh ./docker_build.sh -t $IMAGE
